[env:esp32s3]

platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino

board = esp32-s3-devkitc-1

monitor_speed = 115200
upload_protocol = esptool

; ESP32-S3 N16R8:
; 16 MB QSPI flash
; 8 MB Octal/OPI PSRAM
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DARDUINO_LOOP_STACK_SIZE=16384
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.4.7
    lovyan03/LovyanGFX@1.2.21
    bblanchon/ArduinoJson@7.4.3
