#!/usr/bin/env python3
"""Generate checked-in QR module grids for Radiohead networking.

Requires ``segno`` in the invoking Python environment. Run from the repository
root after changing the mDNS address or setup AP SSID:

    python3 tools/generate_network_qr_codes.py
"""

from dataclasses import dataclass
from pathlib import Path
import re
import sys

try:
    import segno
except ImportError:
    sys.exit("missing segno -- install it in a temporary build environment")

ROOT = Path(__file__).resolve().parent.parent
QUIET_ZONE = 4
ERROR = "m"
WIFI_URI_RESERVED = set('\\;,":')


def read_constant(name: str) -> str:
    source = (ROOT / "include" / "app_state.h").read_text()
    found = re.search(rf'{name}\s*=\s*"([^"]+)"', source)
    if not found:
        sys.exit(f"could not find {name} in include/app_state.h")
    return found.group(1)


@dataclass(frozen=True)
class Target:
    path: str
    namespace: str
    symbol: str
    payload: str
    source_note: str


def pack(matrix):
    size = len(matrix)
    stride = (size + 7) // 8
    data = []
    for row in matrix:
        packed = bytearray(stride)
        for x, dark in enumerate(row):
            if dark:
                packed[x // 8] |= 0x80 >> (x % 8)
        data.extend(packed)
    return stride, data


def write(target: Target) -> None:
    qr = segno.make(target.payload, error=ERROR, micro=False)
    stride, modules = pack(qr.matrix)
    lines = [
        "#pragma once", "", "#include <Arduino.h>", "#include <cstdint>", "",
        "// Generated by tools/generate_network_qr_codes.py. Do not edit by hand.",
        f"// {target.payload}",
        f"// version {qr.version}, error correction {qr.error}, {len(qr.matrix)}x{len(qr.matrix)} modules.",
        f"// {target.source_note}", f"namespace {target.namespace} {{", "",
        f'constexpr const char* {target.symbol} = "{target.payload}";', "",
        f"constexpr int Size = {len(qr.matrix)};", f"constexpr int QuietZone = {QUIET_ZONE};",
        f"constexpr int Stride = {stride};", "",
        "static const uint8_t Modules[] PROGMEM = {",
    ]
    for index in range(0, len(modules), 12):
        lines.append("  " + ", ".join(f"0x{value:02X}" for value in modules[index:index + 12]) + ",")
    lines += ["};", "", f"}}  // namespace {target.namespace}", ""]
    (ROOT / target.path).write_text("\n".join(lines))


def main() -> None:
    address = read_constant("kRadioMdnsAddress")
    setup_ssid = read_constant("kSetupAccessPointSsid")
    if WIFI_URI_RESERVED & set(setup_ssid):
        sys.exit("kSetupAccessPointSsid contains WIFI: URI reserved characters")
    write(Target("include/ConfigQrCode.h", "ConfigQrCode", "Url", f"http://{address}",
                 "Payload derives from kRadioMdnsAddress in include/app_state.h."))
    write(Target("include/SetupWifiQrCode.h", "SetupWifiQrCode", "Payload",
                 f"WIFI:T:nopass;S:{setup_ssid};;",
                 "Payload derives from kSetupAccessPointSsid in include/app_state.h."))


if __name__ == "__main__":
    main()
